spring.application.name=petcare-api

# Conexión con MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/petcare_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Actualización del esquema durante el desarrollo local. Al arrancar, configura Hibernate
# para actualizar automáticamente la estructura de la base de datos según mis entidades JPA
spring.jpa.hibernate.ddl-auto=update

# Mostrar el SQL ejecutado para aprender qué ocurre
spring.jpa.show-sql=true